---
title: "ST 511 HW-2"
author: "Mark Heinen"
format: pdf
editor: visual
---

### Packages

```{r}
library(tidyverse)
```

## Exercise 1: Office Budget

### a.

The random variable is defined as the time, measured in days, between the submission of travel vouchers and their reimbursement of funds.

### b.

$X \sim N(36, 4)$, where X represents the definition given in a.

### c.

$$P(X>55)$$

### d.

A probability distribution represents the range of all possible values of a given random variable, and the probability associated with each possible value.

### e.

The probability that $X>55$ is close to zero because it has a Z-score of $4.75 = \frac{55-36}{4}$, meaning that a value greater than 55 would be at least 4.75 standard deviations from the mean. Important to note the probablities is not zero just close to zero, as anything more than 3 standard deviations above the mean will be greater than the 99.72 percentile.

### f.

Since the probability distribution of our random variable is continouous we can refer to the following equation, $P(x=a) = 0$, which states that for continouous random variables the probability of X being equal to a specific value is 0.

## Exercise 2: Office Budget

### a.




## Exercise 4: Random Sampling

### a.

First step would be to acquire a list of all students currently enrolled at the school, then you should assign each student a number between 1-5000. After that you should generate 50 random numbers that can take on a value between 1-5000, and match each value to student with a matching value. After that comes the extremely difficult task of getting a response from each of your sampled students, in this scenario lets say we hire an RA to track down each student and administer the survey in person. 

### b.

Lets go back to our random sample scenario we created, following the same exact rules, but this time instead of hiring an RA to meticulously track down each student in person, we simply send out an email to our randomly sampled students with a link to our survey. If we don't get back 50 responses we simply eliminate the students who did respond to the survey from the pool of students, and repeat the process until we get back 50 responses. Even in this example we still could have some form of bias in our sample, specifically due to the voluntary nature of the sample we could elicit non-response bias. Which is bias that occurs when responses of individuals who do not respond are characteristically different from the responses of individuals who do respond in surveys/studies. In our case it could be that students who choose to not respond to the survey simply had a neutral opinion regarding the new coach, and lacked the motivation to respond to the survey. While the students who were motivated to take the time to respond to the survey had stronger negative or positive opinions regarding the new coach, thus were more likely to respond to the survey.

## Exerc

