<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>ST 511 Notes</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-d4be639c637f3db3c684c66cefad7e0c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-search-results"></div>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#week-1" id="toc-week-1" class="nav-link active" data-scroll-target="#week-1">#Week 1</a>
  <ul class="collapse">
  <li><a href="#gitgithub" id="toc-gitgithub" class="nav-link" data-scroll-target="#gitgithub">Git/Github</a>
  <ul class="collapse">
  <li><a href="#syntax-for-git" id="toc-syntax-for-git" class="nav-link" data-scroll-target="#syntax-for-git">Syntax for Git</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#week-4" id="toc-week-4" class="nav-link" data-scroll-target="#week-4">Week 4</a>
  <ul class="collapse">
  <li><a href="#random-variable" id="toc-random-variable" class="nav-link" data-scroll-target="#random-variable">Random Variable</a></li>
  <li><a href="#probability-and-sampling-distribution" id="toc-probability-and-sampling-distribution" class="nav-link" data-scroll-target="#probability-and-sampling-distribution">Probability and Sampling Distribution</a>
  <ul class="collapse">
  <li><a href="#normality" id="toc-normality" class="nav-link" data-scroll-target="#normality">Normality</a></li>
  <li><a href="#the-central-limit-theorem" id="toc-the-central-limit-theorem" class="nav-link" data-scroll-target="#the-central-limit-theorem">The Central Limit Theorem</a></li>
  <li><a href="#notation" id="toc-notation" class="nav-link" data-scroll-target="#notation">Notation</a></li>
  </ul></li>
  <li><a href="#finding-average-word-count-in-r" id="toc-finding-average-word-count-in-r" class="nav-link" data-scroll-target="#finding-average-word-count-in-r">Finding Average Word Count in R</a></li>
  </ul></li>
  <li><a href="#week-5-to-6" id="toc-week-5-to-6" class="nav-link" data-scroll-target="#week-5-to-6">Week 5 to 6</a>
  <ul class="collapse">
  <li><a href="#hypothesis-testing" id="toc-hypothesis-testing" class="nav-link" data-scroll-target="#hypothesis-testing">Hypothesis Testing</a>
  <ul class="collapse">
  <li><a href="#assumptions" id="toc-assumptions" class="nav-link" data-scroll-target="#assumptions">Assumptions</a></li>
  <li><a href="#z-distribution" id="toc-z-distribution" class="nav-link" data-scroll-target="#z-distribution">Z-distribution</a></li>
  <li><a href="#notation-1" id="toc-notation-1" class="nav-link" data-scroll-target="#notation-1">Notation</a></li>
  </ul></li>
  <li><a href="#confidence-intervals" id="toc-confidence-intervals" class="nav-link" data-scroll-target="#confidence-intervals">Confidence Intervals</a>
  <ul class="collapse">
  <li><a href="#notation-2" id="toc-notation-2" class="nav-link" data-scroll-target="#notation-2">Notation</a></li>
  <li><a href="#example" id="toc-example" class="nav-link" data-scroll-target="#example">Example</a></li>
  </ul></li>
  <li><a href="#difference-in-proportions-test" id="toc-difference-in-proportions-test" class="nav-link" data-scroll-target="#difference-in-proportions-test">Difference In Proportions Test</a>
  <ul class="collapse">
  <li><a href="#example-1" id="toc-example-1" class="nav-link" data-scroll-target="#example-1">Example</a></li>
  <li><a href="#confidence-interval" id="toc-confidence-interval" class="nav-link" data-scroll-target="#confidence-interval">Confidence Interval</a></li>
  <li><a href="#relationship-between-z-test-and-ci" id="toc-relationship-between-z-test-and-ci" class="nav-link" data-scroll-target="#relationship-between-z-test-and-ci">Relationship Between Z-test and CI</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#week-7" id="toc-week-7" class="nav-link" data-scroll-target="#week-7">Week 7</a>
  <ul class="collapse">
  <li><a href="#central-limit-theorem" id="toc-central-limit-theorem" class="nav-link" data-scroll-target="#central-limit-theorem">Central Limit Theorem</a></li>
  <li><a href="#t-distribution" id="toc-t-distribution" class="nav-link" data-scroll-target="#t-distribution">t-Distribution</a>
  <ul class="collapse">
  <li><a href="#degrees-of-freedom" id="toc-degrees-of-freedom" class="nav-link" data-scroll-target="#degrees-of-freedom">Degrees of Freedom</a></li>
  <li><a href="#connecting-the-dots" id="toc-connecting-the-dots" class="nav-link" data-scroll-target="#connecting-the-dots">Connecting the dots</a></li>
  <li><a href="#mathematical-proof" id="toc-mathematical-proof" class="nav-link" data-scroll-target="#mathematical-proof">Mathematical Proof</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#week-7-1" id="toc-week-7-1" class="nav-link" data-scroll-target="#week-7-1">Week 7</a>
  <ul class="collapse">
  <li><a href="#t-test-math-notation" id="toc-t-test-math-notation" class="nav-link" data-scroll-target="#t-test-math-notation">T-Test Math Notation</a>
  <ul class="collapse">
  <li><a href="#standard-deviation" id="toc-standard-deviation" class="nav-link" data-scroll-target="#standard-deviation">Standard Deviation</a></li>
  <li><a href="#between-groups" id="toc-between-groups" class="nav-link" data-scroll-target="#between-groups">Between Groups</a></li>
  <li><a href="#confidence-interval-1" id="toc-confidence-interval-1" class="nav-link" data-scroll-target="#confidence-interval-1">Confidence Interval</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#week-9-10" id="toc-week-9-10" class="nav-link" data-scroll-target="#week-9-10">Week 9-10</a>
  <ul class="collapse">
  <li><a href="#anova" id="toc-anova" class="nav-link" data-scroll-target="#anova">ANOVA</a>
  <ul class="collapse">
  <li><a href="#tukeys-hsd" id="toc-tukeys-hsd" class="nav-link" data-scroll-target="#tukeys-hsd">Tukeys HSD</a></li>
  <li><a href="#bonferroni" id="toc-bonferroni" class="nav-link" data-scroll-target="#bonferroni">Bonferroni</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#week-11" id="toc-week-11" class="nav-link" data-scroll-target="#week-11">Week 11</a>
  <ul class="collapse">
  <li><a href="#chi-square-test" id="toc-chi-square-test" class="nav-link" data-scroll-target="#chi-square-test">Chi-Square Test</a></li>
  </ul></li>
  <li><a href="#week-12-13" id="toc-week-12-13" class="nav-link" data-scroll-target="#week-12-13">Week 12-13</a>
  <ul class="collapse">
  <li><a href="#linear-regression" id="toc-linear-regression" class="nav-link" data-scroll-target="#linear-regression">Linear Regression</a></li>
  <li><a href="#multiple-linear-regression" id="toc-multiple-linear-regression" class="nav-link" data-scroll-target="#multiple-linear-regression">Multiple Linear Regression</a>
  <ul class="collapse">
  <li><a href="#additive-model" id="toc-additive-model" class="nav-link" data-scroll-target="#additive-model">Additive Model</a></li>
  <li><a href="#interaction-model" id="toc-interaction-model" class="nav-link" data-scroll-target="#interaction-model">Interaction Model</a></li>
  <li><a href="#hypothesis-test-for-multiple-linear-regression" id="toc-hypothesis-test-for-multiple-linear-regression" class="nav-link" data-scroll-target="#hypothesis-test-for-multiple-linear-regression">Hypothesis Test for Multiple Linear Regression</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#week-14-15" id="toc-week-14-15" class="nav-link" data-scroll-target="#week-14-15">Week 14-15</a>
  <ul class="collapse">
  <li><a href="#statistical-inference-vs-sampling-variability" id="toc-statistical-inference-vs-sampling-variability" class="nav-link" data-scroll-target="#statistical-inference-vs-sampling-variability">Statistical Inference vs Sampling Variability</a>
  <ul class="collapse">
  <li><a href="#scenarios" id="toc-scenarios" class="nav-link" data-scroll-target="#scenarios">Scenarios</a></li>
  </ul></li>
  <li><a href="#logistic-regression" id="toc-logistic-regression" class="nav-link" data-scroll-target="#logistic-regression">Logistic Regression</a>
  <ul class="collapse">
  <li><a href="#the-problem" id="toc-the-problem" class="nav-link" data-scroll-target="#the-problem">The Problem</a></li>
  <li><a href="#generalized-linear-model-glm" id="toc-generalized-linear-model-glm" class="nav-link" data-scroll-target="#generalized-linear-model-glm">Generalized Linear Model (GLM)</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">ST 511 Notes</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="week-1" class="level1">
<h1>#Week 1</h1>
<section id="gitgithub" class="level2">
<h2 class="anchored" data-anchor-id="gitgithub">Git/Github</h2>
<section id="syntax-for-git" class="level3">
<h3 class="anchored" data-anchor-id="syntax-for-git">Syntax for Git</h3>
<p>Replace file path with an empty folder path one on your end and change the url to the one you want to copy:</p>
<ul>
<li><code>git clone https://github.com/MH-Stats/Math_Notes.git "C:\Users\mheinen\Documents\Repos\SSH\_Test"</code></li>
</ul>
<p>How to pull files from GitHub repo:</p>
<ul>
<li><code>git pull origin main</code></li>
</ul>
<p>How to commit and upload changes using gitbash:</p>
<ul>
<li>change lib in gitbash <code>cd C:/Users/mheinen/Documents/Repos/SSH_Test</code></li>
</ul>
<p>Check untracked files:</p>
<ul>
<li><code>git status</code></li>
</ul>
<p>Stage specific file:</p>
<ul>
<li><code>git add filename</code></li>
</ul>
<p>Stage all files:</p>
<ul>
<li><code>git add .</code></li>
</ul>
<p>Commit changes: - <code>git commit -m "Add your message here"</code></p>
<p>Push changes to the repo (change main to branch if using a different one): - <code>git push origin main</code></p>
</section>
</section>
</section>
<section id="week-4" class="level1">
<h1>Week 4</h1>
<section id="random-variable" class="level2">
<h2 class="anchored" data-anchor-id="random-variable">Random Variable</h2>
<p>Random variables (RV) are ways to map random or stochastic process to numbers, which is a mathematical object defined as a family of random variables in a probability space, with the most common index fro the family being time. They are the building blocks of probability distributions, and a probability distribution describes the set of all possible values a RV can take and the probability of each value occurring.</p>
<ul>
<li><p>Can be discrete or continuous</p></li>
<li><p>Normally represented by uppercase letters like <span class="math inline">\(X\)</span></p></li>
<li><p>Useful when you know the exact population distribution, as you can use it to calculate probabilities, as an example you know the probability of rolling a 1 through 6 on a dice.</p></li>
</ul>
</section>
<section id="probability-and-sampling-distribution" class="level2">
<h2 class="anchored" data-anchor-id="probability-and-sampling-distribution">Probability and Sampling Distribution</h2>
<p>The probability distribution of a population directly influences the sampling distribution of a statistic drawn from that population. A sampling distribution is essentially the probability distribution of a statistic from all possible samples of a given size.</p>
<p>The spread of the sampling distribution is,</p>
<p><span class="math display">\[\frac{\sigma}{\sqrt{n}}\]</span></p>
<p>Since we normally only get a single sample, we assume that,</p>
<p><span class="math display">\[\bar{x} \approx N(\mu,\frac{\sigma}{\sqrt{n}})\]</span></p>
<ul>
<li>We estimate <span class="math inline">\(\mu\)</span> with <span class="math inline">\(\bar{x}\)</span> and <span class="math inline">\(\sigma\)</span> with <span class="math inline">\(s\)</span></li>
</ul>
<section id="normality" class="level3">
<h3 class="anchored" data-anchor-id="normality">Normality</h3>
<p>If the probability distribution is normal, the sampling distribution will also be normal.</p>
</section>
<section id="the-central-limit-theorem" class="level3">
<h3 class="anchored" data-anchor-id="the-central-limit-theorem">The Central Limit Theorem</h3>
<p>For large independent samples (n&gt;30), regardless of of what the population distribution looks like, the sampling distribution of the sample mean will be normally distributed with mean <span class="math inline">\(\mu\)</span> and standard error of <span class="math inline">\(\frac{\sigma}{\sqrt{n}}\)</span></p>
<p>Z and t-test assume the sampling distribution is normally distributed. This is also why:</p>
<ul>
<li><span class="math inline">\(\bar{x}\)</span> is unbiased estimator for <span class="math inline">\(\mu\)</span></li>
</ul>
</section>
<section id="notation" class="level3">
<h3 class="anchored" data-anchor-id="notation">Notation</h3>
<p>To write the mean and standard deviation in a distribution you can write it as,</p>
<p><span class="math display">\[X \sim N(\mu, \sigma)\]</span></p>
<p>When writing out the probability you can write it as,</p>
<p><span class="math display">\[P(X&gt;x) \qquad \text{where } X \text{ is the random variable, } x \text{ is the value, and &gt; is greater than (can be &gt;, &lt;, =, etc.)}\]</span></p>
</section>
</section>
<section id="finding-average-word-count-in-r" class="level2">
<h2 class="anchored" data-anchor-id="finding-average-word-count-in-r">Finding Average Word Count in R</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr) <span class="co">#Used for str_split</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Creating a character vector from the address </span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>address <span class="ot">&lt;-</span> <span class="st">"Four score and seven years ago our fathers brought forth on this continent, a new nation, conceived in Liberty, and dedicated to the proposition that all men are created equal.</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="st">Now we are engaged in a great civil war, testing whether that nation, or any nation so conceived and so dedicated, can long endure. We are met on a great battle-field of that war. We have come to dedicate a portion of that field, as a final resting place for those who here gave their lives that that nation might live. It is altogether fitting and proper that we should do this.</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="st">But, in a larger sense, we can not dedicate -- we can not consecrate -- we can not hallow -- this ground. The brave men, living and dead, who struggled here, have consecrated it, far above our poor power to add or detract. The world will little note, nor long remember what we say here, but it can never forget what they did here. It is for us the living, rather, to be dedicated here to the unfinished work which they who fought here have thus far so nobly advanced. It is rather for us to be here dedicated to the great task remaining before us -- that from these honored dead we take increased devotion to that cause for which they gave the last full measure of devotion -- that we here highly resolve that these dead shall not have died in vain -- that this nation, under God, shall have a new birth of freedom -- and that government of the people, by the people, for the people, shall not perish from the earth."</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>address_count <span class="ot">&lt;-</span> <span class="fu">str_split</span>(address, <span class="st">"</span><span class="sc">\\</span><span class="st">W+"</span>) <span class="co">#Splits up the text by " " and removes white space and other non-letter chars from address</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>address_clean <span class="ot">&lt;-</span> address_count[[<span class="dv">1</span>]][<span class="sc">-</span><span class="dv">273</span>] <span class="co">#Removes last element which was null aka ""</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>address_clean[<span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>] <span class="co">#Using indexing to show a snippet of what the character vector now looks like</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Four"      "score"     "and"       "seven"     "years"     "ago"      
 [7] "our"       "fathers"   "brought"   "forth"     "on"        "this"     
[13] "continent" "a"         "new"       "nation"    "conceived" "in"       
[19] "Liberty"   "and"      </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>avg_length <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">nchar</span>(address_clean)) <span class="co">#nchar is a built in R function to tell you character length</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Paste allows you to put multiple inputs into a function like print()</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"The average word length in the Gettysburg Address is"</span>, avg_length))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "The average word length in the Gettysburg Address is 4.22426470588235"</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">24</span>) <span class="co">#Setting seed</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>address_sample <span class="ot">&lt;-</span> <span class="fu">sample</span>(address_clean, <span class="dv">10</span>) <span class="co">#Sampling 10 words from the cleaned address vector</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>avg_sample_length <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">nchar</span>(address_sample))</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"The average word length in the sample of the Gettysburg Address is"</span>, avg_sample_length))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "The average word length in the sample of the Gettysburg Address is 5.9"</code></pre>
</div>
</div>
</section>
</section>
<section id="week-5-to-6" class="level1">
<h1>Week 5 to 6</h1>
<section id="hypothesis-testing" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis-testing">Hypothesis Testing</h2>
<section id="assumptions" class="level3">
<h3 class="anchored" data-anchor-id="assumptions">Assumptions</h3>
<p>Must check that the data has two thing:</p>
<ul>
<li><p>Independence</p></li>
<li><p>Normality</p>
<ul>
<li>Data must be “normal” meaning the sample size n must satisfy two conditions:
<ul>
<li><span class="math inline">\(n * \pi_0\geq10\)</span></li>
<li><span class="math inline">\(n * (1-\pi_0)\geq10\)</span></li>
</ul></li>
</ul></li>
</ul>
</section>
<section id="z-distribution" class="level3">
<h3 class="anchored" data-anchor-id="z-distribution">Z-distribution</h3>
<p>Z-score is a ratio of how the sample proportion differs from the hypothesized proportion (<span class="math inline">\(p_0\)</span>) as compared to the expected variability of the <span class="math inline">\(\hat{p}\)</span> (sample proportion) values.</p>
<p><span class="math display">\[Z = \frac{\hat{p}-p_0}{\sqrt{\frac{p_0(1-p_0)}{n}}}\]</span></p>
<ul>
<li>The standard error, which is the the standard deviation of the sampling distribution comes from the above formula,</li>
</ul>
<p><span class="math display">\[SE=\sqrt{\frac{p_0(1-p_0)}{n}}\]</span></p>
<p>When the null hypothesis is true and the conditions are met, Z has a standard normal distribution.</p>
</section>
<section id="notation-1" class="level3">
<h3 class="anchored" data-anchor-id="notation-1">Notation</h3>
<p>When writing null and alternative hypothesis follow the following syntax based on if your data is quantitative or categorical:</p>
<p>Quantitative</p>
<ul>
<li><p>Your hypothesis are about a population mean</p></li>
<li><p>Use <span class="math inline">\(\mu\)</span>, as an example say your testing that the average height of a population is 64 inches, but you believe the true average height is greater than 64</p></li>
</ul>
<p><span class="math display">\[
\begin{align*}
H_0 &amp;: \mu = 64 \\
H_a &amp;: \mu &gt; 64
\end{align*}
\]</span></p>
<p>Categorical</p>
<ul>
<li>Use <span class="math inline">\(\pi\)</span> when your dealing with categorical data, as you are testing the hypothesis about a population proportion. As an example say you want to test if 25% of people prefer sleeping with their socks on.</li>
</ul>
<p><span class="math display">\[
\begin{align*}
H_0 &amp;: \pi = .25 \\
H_a &amp;: \pi \ne .25
\end{align*}
\]</span></p>
</section>
</section>
<section id="confidence-intervals" class="level2">
<h2 class="anchored" data-anchor-id="confidence-intervals">Confidence Intervals</h2>
<p>The goal of a confidence interval is to create a sampling distribution around our statistic, and use the standard error (sampling variability) to provide a range of values to estimate our population parameter.</p>
<p>A confidence interval is a derived from the successes and failures of our random sample, while hypothesis testing is the successes and failures under the assumption of the null hypothesis.</p>
<section id="notation-2" class="level3">
<h3 class="anchored" data-anchor-id="notation-2">Notation</h3>
<p>Formula:</p>
<p><span class="math display">\[\hat{p}\pm MOE\]</span></p>
<p>Margin of Error (MOE):</p>
<p><span class="math display">\[z^* * \sqrt{\frac{\hat{p}(1-\hat{p})}{n}}\]</span></p>
<ul>
<li>The square root in the formula is equal to <span class="math inline">\(SE(\hat{p})\)</span></li>
</ul>
</section>
<section id="example" class="level3">
<h3 class="anchored" data-anchor-id="example">Example</h3>
<p>We want to estimate the number of NC State students that eat ice cream. Let’s assume that 100 NC State students were randomly sampled, and it turned out that <span class="math inline">\(\hat{p}=0.37\)</span>. This is our best guess for π, which nobody thinks is actually correct.</p>
<p>We need to check for a couple things and note our variables of interest:</p>
<ul>
<li><p>Independence</p></li>
<li><p><span class="math inline">\(\hat{p}=0.37\)</span></p></li>
<li><p><span class="math inline">\(n=100\)</span></p></li>
<li><p>Success/Failure:</p></li>
</ul>
<p><span class="math display">\[SE(\hat{p})=\sqrt{\frac{0.37(1-0.37)}{100}}=0.0482\]</span></p>
<p>Now we can calculate a 95% confidence interval:</p>
<p><span class="math display">\[0.37 \pm 1.96 * 0.0428=(0.286, 0.454)\]</span></p>
<p>Two ways to state in words:</p>
<ol type="1">
<li><p>We are 95% confident <span class="math inline">\(\pi\)</span> is within (0.286, 0.454).</p></li>
<li><p>We are 95% confident that the true proportion of NC State students who eat Howling Cow ice cream at dinner is between 0.286 and 0.454.</p></li>
</ol>
</section>
</section>
<section id="difference-in-proportions-test" class="level2">
<h2 class="anchored" data-anchor-id="difference-in-proportions-test">Difference In Proportions Test</h2>
<p>Also know as a two-proportion z-test. It is a z-test used to determine whether the difference between the proportions of two groups, coming from a binomial distribution is statistical significant.</p>
<section id="example-1" class="level3">
<h3 class="anchored" data-anchor-id="example-1">Example</h3>
<p>A pharmaceutical company is conducting a clinical trial to test the effectiveness of a new drug for a common illness. They randomly assign participants to one of two groups</p>
<p>Group 1 (New Drug): Out of 200 patients, 160 recovered from the illness.</p>
<p>Group 2 (Placebo): Out of 180 patients, 126 recovered from the illness.</p>
<p>Perform a hypothesis test to determine if the proportion of patients who recovered is significantly different for the group that received the new drug</p>
<section id="notation-3" class="level4">
<h4 class="anchored" data-anchor-id="notation-3">Notation</h4>
<p><span class="math inline">\(H_o:\pi_n-\pi_p=0\)</span></p>
<p><span class="math inline">\(H_a:\pi_n-\pi_p&gt;0\)</span></p>
<p><span class="math inline">\(\hat{p}_n - \hat{p}_p=.1\)</span></p>
</section>
<section id="assumptions-1" class="level4">
<h4 class="anchored" data-anchor-id="assumptions-1">Assumptions</h4>
<ul>
<li><p>Independence (observation level, not variables)</p></li>
<li><p>Success-failure (sample size)</p></li>
</ul>
<p><img src="Images\pool.png" class="img-fluid"></p>
<ul>
<li>You need to check both <span class="math inline">\(p_1\)</span> &amp; <span class="math inline">\(p_2\)</span> by using the pooled proportion multiplied by the sample size n for each sample.
<ul>
<li>is <span class="math inline">\(p_{pool} * n_1&gt;10\)</span></li>
<li>is <span class="math inline">\((1-p_{pool})*n_1&gt;10\)</span></li>
<li>is <span class="math inline">\(p_{pool}*n_2&gt;10\)</span></li>
<li>is <span class="math inline">\((1-p_{pool})*n_2&gt;10\)</span></li>
</ul></li>
</ul>
</section>
<section id="z-test" class="level4">
<h4 class="anchored" data-anchor-id="z-test">Z-test</h4>
<p><img src="Images\zpool.png" class="img-fluid"></p>
<p><span class="math display">\[
Z=\frac{.1-0}{\sqrt{.744*.226(\frac{1}{200}+\frac{1}{180})}}=2.327
\]</span></p>
</section>
<section id="conclusion" class="level4">
<h4 class="anchored" data-anchor-id="conclusion">Conclusion</h4>
<p>Because or p-value is &lt; α, we reject the null hypothesis, and have strong evidence to conclude that the true proportion of patients who recovered from the illness taking the new drug is larger than those who took the placebo.</p>
</section>
</section>
<section id="confidence-interval" class="level3">
<h3 class="anchored" data-anchor-id="confidence-interval">Confidence Interval</h3>
<section id="assumptions-2" class="level4">
<h4 class="anchored" data-anchor-id="assumptions-2">Assumptions</h4>
<ul>
<li><p>Independence</p></li>
<li><p>Success-failure</p>
<ul>
<li><span class="math inline">\(\hat{p}_n*n_1&gt;10\)</span>
<ul>
<li><span class="math inline">\(.8*200&gt;10\)</span></li>
</ul></li>
<li><span class="math inline">\((1-\hat{p}_n)*n_1&gt;10\)</span>
<ul>
<li><span class="math inline">\(.2*200&gt;10\)</span></li>
</ul></li>
<li><span class="math inline">\(\hat{p}_p*n_2&gt;10\)</span>
<ul>
<li><span class="math inline">\(.7*180&gt;10\)</span></li>
</ul></li>
<li><span class="math inline">\((1-\hat{p}_p)*n_2&gt;10\)</span>
<ul>
<li><span class="math inline">\(.3*180&gt;10\)</span></li>
</ul></li>
</ul></li>
</ul>
</section>
<section id="ci" class="level4">
<h4 class="anchored" data-anchor-id="ci">CI</h4>
<p><img src="Images\CI_prop.png" class="img-fluid"></p>
<p><span class="math display">\[
\sqrt{\frac{.8*.2}{200}+\frac{.7*.3}{180}}=0.00443
\]</span></p>
<p><img src="Images\lab_plot.png" class="img-fluid"></p>
<ul>
<li><span class="math inline">\(.1+.00433*1.96=0.109\)</span></li>
<li><span class="math inline">\(.1-.00443*1.96=0.091\)</span></li>
</ul>
<p>We are 95% confident that the true proportion of patients who took the new drug and recovered is 0.091 to 0.109 HIGHER than the true proportion of patients who took the placebo and recovered.</p>
</section>
</section>
<section id="relationship-between-z-test-and-ci" class="level3">
<h3 class="anchored" data-anchor-id="relationship-between-z-test-and-ci">Relationship Between Z-test and CI</h3>
<p>When working with a two-tailed test, if you reject the null hypothesis at <span class="math inline">\(\alpha=0.05\)</span> level, we would expect our 95% CI to not include the null values.</p>
<p>The condition for rejecting the null hypothesis is that the absolute Z-statistic is greater than the critical value,</p>
<p><span class="math display">\[
|Z_{stat}|&gt;Z_{crit}
\]</span></p>
<p>Which can be rearranged to show,</p>
<p><span class="math display">\[
|\hat{p}-p_0|&gt;Z_{crit}\sqrt{\frac{\hat{p}(1-\hat{p})}{n}}
\]</span></p>
<p>For <strong>quantitative variables</strong>, the key insight is that when you reject the null hypothesis, the distance between your statistic and the null value is larger than the margin of error of the confidence interval. Since the null value is a certain distance away from your sample proportion, and that distance is greater than the width of your confidence interval, the null value cannot possibly be inside the interval.</p>
</section>
</section>
</section>
<section id="week-7" class="level1">
<h1>Week 7</h1>
<section id="central-limit-theorem" class="level2">
<h2 class="anchored" data-anchor-id="central-limit-theorem">Central Limit Theorem</h2>
<p><img src="Images\cltmean.png" class="img-fluid"></p>
<p><img src="Images\cltmean_2.png" class="img-fluid"></p>
</section>
<section id="t-distribution" class="level2">
<h2 class="anchored" data-anchor-id="t-distribution">t-Distribution</h2>
<p>Similar to normal distribution, but has more uncertainty.</p>
<ul>
<li><p>There are infinite t-distributions vs.&nbsp;the singular normal distribution</p></li>
<li><p>t-distribution approach a normal distribution as you increase your degrees of freedom.</p></li>
<li><p>Used when the population standard deviation is unknown.</p></li>
<li><p>Used for quantitative data.</p></li>
</ul>
<section id="degrees-of-freedom" class="level3">
<h3 class="anchored" data-anchor-id="degrees-of-freedom">Degrees of Freedom</h3>
<p>DF for a t-distribution refer to the number of independent pieces of information that available to estimate a parameter. In the context of the t-distribution, DF are a parameter that determines the shape of the distribution.</p>
<ul>
<li><span class="math inline">\(DF = n-1\)</span></li>
</ul>
<p>DF correct for the uncertainty introduced when estimating the population standard deviation using the sample deviation when working with a quantitative variable.</p>
<p>Since the standard error of the sampling distribution is known for hypothesis test with categorical data, derived from <span class="math inline">\(\pi_o\)</span> , we don’t correct with t, instead we use the standard normal distribution.</p>
</section>
<section id="connecting-the-dots" class="level3">
<h3 class="anchored" data-anchor-id="connecting-the-dots">Connecting the dots</h3>
<p>If the hypothesis test leads you to reject the null hypothesis, it means that the distance between <span class="math inline">\(\bar{x}\)</span> and <span class="math inline">\(u_o\)</span> is greater than the margin of error defined by the 95% CI.</p>
<p><img src="Images\t_test.png" class="img-fluid"></p>
</section>
<section id="mathematical-proof" class="level3">
<h3 class="anchored" data-anchor-id="mathematical-proof">Mathematical Proof</h3>
<p><span class="math display">\[
|\frac{\bar{x}_1-u_o}{SE}|&gt;t^*
\]</span></p>
<p><span class="math display">\[
|\bar{x}_1-u_o|&gt;t^**SE
\]</span></p>
<p>This inequality states that the distance from the center of the interval to the null value <span class="math inline">\(μ_o\)</span> is greater than the margin of error. If the distance to <span class="math inline">\(μ_o\)</span> is longer than the margin of error around the sample mean, the confidence interval must exclude <span class="math inline">\(μ_o\)</span>.</p>
<p>These two equations are mathematically equivalent, proving that rejecting <span class="math inline">\(H_o\)</span> is the same as the confidence interval excluding the null value <span class="math inline">\(u_o\)</span>.</p>
<ul>
<li>For a two-side test where <span class="math inline">\(\alpha\)</span> “matches” with our confidence interval you would get something like, <span class="math inline">\(\alpha=0.05\)</span> and a 95% CI.</li>
</ul>
<p>With categorical data the difference in their numerical values is usually too small to break the equivalence.</p>
</section>
</section>
</section>
<section id="week-7-1" class="level1">
<h1>Week 7</h1>
<section id="t-test-math-notation" class="level2">
<h2 class="anchored" data-anchor-id="t-test-math-notation">T-Test Math Notation</h2>
<p><img src="Images\ttest_equ.jpg" class="img-fluid"></p>
<section id="standard-deviation" class="level3">
<h3 class="anchored" data-anchor-id="standard-deviation">Standard Deviation</h3>
<p><img src="Images\sd_formula.webp" class="img-fluid"></p>
</section>
<section id="between-groups" class="level3">
<h3 class="anchored" data-anchor-id="between-groups">Between Groups</h3>
<p><img src="Images\tdiff_test.png" class="img-fluid"></p>
</section>
<section id="confidence-interval-1" class="level3">
<h3 class="anchored" data-anchor-id="confidence-interval-1">Confidence Interval</h3>
<p>Need to know the margin of error, which you should <span class="math inline">\(\pm\)</span> from your best guess.</p>
<p><img src="Images\ME_t_test.png" class="img-fluid"></p>
</section>
</section>
</section>
<section id="week-9-10" class="level1">
<h1>Week 9-10</h1>
<section id="anova" class="level2">
<h2 class="anchored" data-anchor-id="anova">ANOVA</h2>
<p>ANOVA is an extension from difference in means, where the test statistic is the variability (variance) within group vs the variability (variance) across groups.</p>
<section id="hypothesis-notation" class="level4">
<h4 class="anchored" data-anchor-id="hypothesis-notation">Hypothesis Notation:</h4>
<p>Example text comes from the plants dataset in R.</p>
<p><span class="math display">\[
H_o: \mu_c = \mu_{trt1} = \mu_{trt2}
\]</span></p>
<p><strong>In words:</strong></p>
<ul>
<li><p><span class="math inline">\(H_o:\)</span> The population mean weight of plants across the three groups are equal.</p></li>
<li><p><span class="math inline">\(H_a:\)</span> At least one population mean plant weight is different across the three groups.</p></li>
</ul>
<p>Note: It is uncommon to write our the alternative hypothesis in notation, but the null is generally written in proper notation.</p>
</section>
<section id="assumptions-3" class="level4">
<h4 class="anchored" data-anchor-id="assumptions-3">Assumptions</h4>
<p><strong>Independence</strong></p>
<ul>
<li><p>Between groups</p></li>
<li><p>Across groups</p></li>
</ul>
<p><strong>Normality</strong></p>
<ul>
<li><p>Check using quantiles and a Normal q-q plot to determine if the data is normally distributed.</p>
<ul>
<li><p>We plot the values from our data set against what woe would expect the values to look like if they were normally distributed</p></li>
<li><p>If the dots roughly follow a straight line, we have evidence of normality.</p></li>
</ul></li>
</ul>
<p><img src="\Images\normal_qq.png" class="img-fluid"></p>
<p><img src="\Images\right_qq.png" class="img-fluid"></p>
<p><strong>Equal variance</strong></p>
<p>General rule: Is the largest sample standard deviation more than twice the smallest sample standard deviation?</p>
</section>
<section id="the-math-behind-anova" class="level4">
<h4 class="anchored" data-anchor-id="the-math-behind-anova">The Math Behind ANOVA</h4>
<p><span class="math display">\[
F = \frac{MS_{Between}}{MS_{Within}} \\
F = \frac{\frac{SS_{Between}}{k-1}}{\frac{SS_{Within}}{N-k}} \\
SS_{Between} = \sum^k_{i=1}n_i(\bar{X}_i-\bar{X}_{grand})^2 \\
SS_{Within} = \sum^k_{i=1}\sum^{n_i}_{j=1}(X_{ij}-\bar{X}_i)^2
\]</span></p>
<ul>
<li><p>SS means sum of squares</p></li>
<li><p>F is our statistics</p></li>
</ul>
<section id="definitions" class="level5">
<h5 class="anchored" data-anchor-id="definitions">Definitions</h5>
<p>The Sum of Squares (SS) is a measure of total variability (between or within)</p>
<p>The Mean Squares (MS) is an estimate (<span class="math inline">\(s^2\)</span>) of the population variance (<span class="math inline">\(\sigma^2\)</span>), represented as,</p>
<p><span class="math display">\[
s^2=\frac{\sum(x_i-\bar{x})^2}{n-1}
\]</span></p>
<ul>
<li>This is the <span class="math inline">\(\frac{SS}{df}\)</span></li>
</ul>
</section>
</section>
<section id="f-distribution" class="level4">
<h4 class="anchored" data-anchor-id="f-distribution">F Distribution</h4>
<p>A continuous, positively skewed probability distribution, characterized by two degrees of freedom (numerator and denominator) that determine its shape.</p>
<ul>
<li>Always one tail no matter what</li>
</ul>
<section id="degrees-of-freedom-1" class="level5">
<h5 class="anchored" data-anchor-id="degrees-of-freedom-1">Degrees of Freedom</h5>
<p>Degrees of Freedom (df) is the number of independent pieces of information used to calculate the statistic</p>
<p>When we estimate the population (grand) mean, there are <span class="math inline">\(k-1\)</span> independent pieces of information</p>
<p>When we estimate the population means within each group, there are <span class="math inline">\(n - k\)</span> independent pieces of information</p>
</section>
<section id="f-statistic" class="level5">
<h5 class="anchored" data-anchor-id="f-statistic">F-Statistic</h5>
<p>The whole goal of Anova is to compare the variability between groups vs the variability within groups.</p>
</section>
</section>
<section id="tukeys-hsd" class="level3">
<h3 class="anchored" data-anchor-id="tukeys-hsd">Tukeys HSD</h3>
<p>The main idea of the hsd is to compute the honestly significant difference (hsd) between all pairwise comparisons</p>
<section id="type-1-error" class="level4">
<h4 class="anchored" data-anchor-id="type-1-error">Type 1 Error</h4>
<p><span class="math inline">\(\alpha\)</span> is our significance level, and our Type I error rate.</p>
<ul>
<li>A <strong>Type I error</strong> is the risk rejecting the null hypothesis when the null hypothesis is actually true.
<ul>
<li>As an example when <span class="math inline">\(\alpha=0.05\)</span> that means you have a 5% risk of rejecting the null hypothesis when it is actually true.</li>
</ul></li>
</ul>
</section>
<section id="family-wise-error-rate" class="level4">
<h4 class="anchored" data-anchor-id="family-wise-error-rate">Family-Wise Error Rate</h4>
<p>Family-wise error rate (FWER) is the probability/risk of making one or more Type I error across all tests in a family of comparisons. It is a way to quantify the risk of making Type I errors during multiple hypothesis testing.</p>
<p>The formula is,</p>
<p><span class="math display">\[
FWER = 1 - (1-\alpha)^m
\]</span></p>
<p>Where <span class="math inline">\(m\)</span> is the number of comparisons.</p>
<p><span class="math display">\[
\text{k choose 2} = \frac{k(k-1)}{2}
\]</span></p>
</section>
<section id="pairwise-comparisons" class="level4">
<h4 class="anchored" data-anchor-id="pairwise-comparisons">Pairwise Comparisons</h4>
<p>Commonly we report confidence intervals to estimate which means are actually different (also reports p-values)</p>
<p>Tukey’s HSD can be represented as,</p>
<p><span class="math display">\[
\bar{x}_1-\bar{x}_2 \pm q^**\sqrt{MSE*\frac{1}{n_j}+\frac{1}{n_{j}^*}}
\]</span></p>
<p>Where:</p>
<ul>
<li><p><span class="math inline">\(q^*\)</span> is a value from the studentized range distribution</p></li>
<li><p>(MSE) refers to the average of the squared differences between individual data points within each group and their respective group mean, divided by the degrees of freedom. Also know as the estimated variance by pooling all the groups.</p></li>
</ul>
<p><span class="math display">\[
MSE = \sum^k_{i=1}\frac{(n_i-1)s^2_i}{N-k}
\]</span></p>
<section id="how-to-find-q" class="level5">
<h5 class="anchored" data-anchor-id="how-to-find-q">How to find <span class="math inline">\(q^*\)</span></h5>
<p>Can be found using the <code>qtukey()</code> function</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qtukey</span>(<span class="at">p =</span> <span class="fl">0.95</span>, <span class="at">nmeans =</span> <span class="dv">3</span>, <span class="at">df =</span> <span class="dv">27</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.506426</code></pre>
</div>
</div>
</section>
</section>
<section id="test-statistic" class="level4">
<h4 class="anchored" data-anchor-id="test-statistic">Test-statistic</h4>
<p><span class="math display">\[
Q = \frac{\bar{x}_i-\bar{x}_j}{\sqrt{\frac{MSE}{2}(\frac{1}{n_i}+\frac{1}{n_j})}}
\]</span></p>
</section>
<section id="summary" class="level4">
<h4 class="anchored" data-anchor-id="summary">Summary</h4>
<p>Tukey’s Honest Significant Difference (HSD) test is a post hoc test commonly used to assess the significance of differences between pairs of group means. Tukey HSD is often a follow up to one-way ANOVA, when the F-test has revealed the existence of a significant difference between some of the tested groups.</p>
</section>
</section>
<section id="bonferroni" class="level3">
<h3 class="anchored" data-anchor-id="bonferroni">Bonferroni</h3>
<p>Tukey’s HSD is best for making all possible pairwise comparisons, while <strong>Bonferroni Correction</strong> is more general and suited for a small number of pre-planned comparisons.</p>
<p>You conduct individual t-tests, but divide by the original significance level <span class="math inline">\(\alpha\)</span> by the number of tests being performed (<span class="math inline">\(m\)</span>)</p>
</section>
</section>
</section>
<section id="week-11" class="level1">
<h1>Week 11</h1>
<section id="chi-square-test" class="level2">
<h2 class="anchored" data-anchor-id="chi-square-test">Chi-Square Test</h2>
<p>The big idea is to compare expected counts (the assumed counts under the null hypothesis) with the observed counts (your results). This is used to calculate the test statistic.</p>
<section id="hypothesis-notation-1" class="level4">
<h4 class="anchored" data-anchor-id="hypothesis-notation-1">Hypothesis Notation</h4>
<p>Ho: Sex and species of penguins are independent</p>
<p>Ha: sex and species of penguins are not independent</p>
<p>Remember for the null this means species has no impact <strong>OR</strong> species is completely independent from sex. While for the alternative this means species has some impact on sex <strong>OR</strong> species is not independent from sex.</p>
<section id="assumptions-4" class="level5">
<h5 class="anchored" data-anchor-id="assumptions-4">Assumptions</h5>
<ul>
<li>Independence</li>
</ul>
<p><img src="Images\chi_ind.png" class="img-fluid"></p>
<ul>
<li><p>Expected Frequencies</p>
<ul>
<li>Expected cell count should be &gt; 5</li>
<li>If any of the expected values are low, the p-values generated by the test start to lose reliability. Should check this in our table.</li>
</ul></li>
</ul>
</section>
</section>
<section id="chi-square-distribution" class="level4">
<h4 class="anchored" data-anchor-id="chi-square-distribution">Chi-Square Distribution</h4>
<p>Binomial Approximation: The observed Counts in a contingency table follow a binomial distribution</p>
<p>The Central limit theorem tells us that when the number of trials (<span class="math inline">\(n\)</span>) is large enough, the binomial distribution can be reasonably approximated by the normal distribution</p>
<p>The Chi-Square test relies on the assumption that the sampling distribution of the observed frequencies (counts) is close enough to a normal distribution for the <span class="math inline">\(X^2\)</span> statistic to accurately follow the theoretical Chi-Square distribution</p>
<p>When Expected Counts are high (<span class="math inline">\(\geq5\)</span>): The underlying discrete (integer) count data behaves smoothly, like a continuous bell-shapped (Normal) curve</p>
<p>When Expected Counts are low (<span class="math inline">\(&lt;5\)</span>): The data distribution remains highly skewed and chunky (discrete). It looks nothing like the smooth Normal distribution.</p>
<p>If our sample size assumption (expected counts) is not met, the test statistic doesn’t actually follow the distribution it’s being compared to…. so we can’t trust the results.</p>
</section>
<section id="expected-counts" class="level4">
<h4 class="anchored" data-anchor-id="expected-counts">Expected Counts</h4>
<p>To calculate the expected count for the <span class="math inline">\(i^{th}\)</span> row and <span class="math inline">\(j^{th}\)</span> column,</p>
<p><span class="math display">\[
\text{Expected Count}_{\text{row i, col j}} = \frac{\text{(row i total)}*\text{(col j total)}}{\text{table total}}
\]</span></p>
<p><img src="Images\expected_counts.png" class="img-fluid"></p>
<p><img src="Images\expected2.png" class="img-fluid"></p>
</section>
<section id="test-statistic-1" class="level4">
<h4 class="anchored" data-anchor-id="test-statistic-1">Test Statistic</h4>
<p><img src="\Images\chisq.png" class="img-fluid"></p>
<ul>
<li><p><span class="math inline">\(r\)</span> is the number of groups for one variable (rows)</p></li>
<li><p><span class="math inline">\(c\)</span> is the number of groups for the second variable (columns)</p></li>
<li><p>The test statistic cannot be negative</p></li>
</ul>
<section id="p-value" class="level5">
<h5 class="anchored" data-anchor-id="p-value">p-value</h5>
<p>To calculate the p-value you can use <code>chisq_test(data, var1 ~ var2)</code></p>
</section>
<section id="notation-4" class="level5">
<h5 class="anchored" data-anchor-id="notation-4">Notation</h5>
<p>The probability of observing our statistic, or something larger given the null hypothesis is true.</p>
<ul>
<li><p><span class="math inline">\(P(\chi^2 \geq X^2) = \text{p-value}\)</span></p>
<ul>
<li><p><span class="math inline">\(\chi^2\)</span> = map of possible outcomes on the chi-square distribution (random variable because it is generated from a random process)</p></li>
<li><p><span class="math inline">\(X^2\)</span> = your statistic</p></li>
</ul></li>
</ul>
</section>
</section>
<section id="important-notes" class="level4">
<h4 class="anchored" data-anchor-id="important-notes">Important Notes</h4>
<ul>
<li><p>The shape of the Chi-Square distribution curve depends on the degrees of freedom</p></li>
<li><p>The chi-square distribution is skewed to the right, and the chi-square test is always right-tailed</p></li>
<li><p>A chi-square test cannot have a directional hypothesis. A chi-square value can only indicate that a relationship exists between two variables, not what the relationship is.</p></li>
</ul>
</section>
<section id="chi-square-difference-in-proportions" class="level4">
<h4 class="anchored" data-anchor-id="chi-square-difference-in-proportions">Chi-Square Difference in Proportions</h4>
<p><img src="Images\chi_dp.png" class="img-fluid"></p>
<p><img src="Images\show_it.png" class="img-fluid"></p>
<p><strong>Z-Statistic</strong></p>
<p><span class="math display">\[
Z = \frac{(\hat{p}_1-\hat{p}_2)}{SE_{pooled}} = \frac{(0.5385 -0.3684)}{0.1786} = \frac{0.1701}{0.1786} \approx 0.952
\]</span></p>
<p><span class="math display">\[
.952^2 = .906
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>counts_table <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">7</span>,<span class="dv">7</span>,<span class="dv">6</span>,<span class="dv">12</span>), <span class="at">nrow =</span> <span class="dv">2</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.test</span>(counts_table, <span class="at">correct =</span> F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    2-sample test for equality of proportions without continuity correction

data:  counts_table
X-squared = 0.90688, df = 1, p-value = 0.3409
alternative hypothesis: two.sided
95 percent confidence interval:
 -0.177065  0.517146
sample estimates:
   prop 1    prop 2 
0.5384615 0.3684211 </code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="week-12-13" class="level1">
<h1>Week 12-13</h1>
<section id="linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="linear-regression">Linear Regression</h2>
<section id="summary-statistics" class="level4">
<h4 class="anchored" data-anchor-id="summary-statistics">Summary Statistics</h4>
<p>Correlation (r):</p>
<ul>
<li><p>Is bounded between [-1, 1]</p></li>
<li><p>Measures the strength + direction of a linear relationship</p></li>
<li><p>The correlation value has no units and is not impacted by a linear change in units (e.g.&nbsp;going from inches to centimeters)</p></li>
</ul>
<p><img src="Images\r_corr.webp" class="img-fluid"></p>
<p>Slope + intercept (fit a line)</p>
</section>
<section id="syntax" class="level4">
<h4 class="anchored" data-anchor-id="syntax">Syntax</h4>
<p><code>cor(x, y)</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ purrr     1.0.2
✔ forcats   1.0.0     ✔ readr     2.1.5
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>airquality <span class="sc">|&gt;</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">corr =</span> <span class="fu">cor</span>(Wind, Temp, <span class="at">use =</span> <span class="st">"complete.obs"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        corr
1 -0.4579879</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>airquality <span class="sc">|&gt;</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Wind, <span class="at">y =</span> Temp)) <span class="sc">+</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">'lm'</span>, <span class="at">se =</span> F, <span class="at">formula =</span> <span class="st">'y ~ x'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ST_511_Notes_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="residual" class="level4">
<h4 class="anchored" data-anchor-id="residual">Residual</h4>
<p>The residual of the <span class="math inline">\(i^{th}\)</span> observation <span class="math inline">\((x_i,y_i)\)</span> is the difference of the observed outcome and the outcome we would predict based on the model fit:</p>
<p><span class="math display">\[e_i = y_i-\hat{y}_i\]</span></p>
<ul>
<li><p><span class="math inline">\(y_i\)</span> is an observed value.</p></li>
<li><p><span class="math inline">\(\hat{y}_i\)</span> is the predicted value based on the line. It is typically found by plugging <span class="math inline">\(x_i\)</span> into the model.</p></li>
</ul>
<p>To minimize the residual sum of squares:</p>
<p><span class="math display">\[
\sum(y_i-\hat{y})^2
\]</span></p>
<section id="residual-overlay-plot" class="level5">
<h5 class="anchored" data-anchor-id="residual-overlay-plot">Residual Overlay Plot:</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fitting a linear model</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>air_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(Wind <span class="sc">~</span> Temp, <span class="at">data =</span> airquality) </span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Adding fitted and residuals </span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>airquality<span class="sc">$</span>fit  <span class="ot">&lt;-</span> <span class="fu">fitted</span>(air_lm)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>airquality<span class="sc">$</span>res  <span class="ot">&lt;-</span> <span class="fu">resid</span>(air_lm)</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating residual overlay plot</span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(airquality, <span class="fu">aes</span>(Temp, Wind)) <span class="sc">+</span></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>(<span class="fu">aes</span>(<span class="at">xend =</span> Temp, <span class="at">yend =</span> fit), <span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span> </span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> F, <span class="at">formula =</span> y <span class="sc">~</span> x, <span class="at">color =</span> <span class="st">"purple"</span>) <span class="sc">+</span></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Residuals"</span>, <span class="at">y =</span> <span class="st">"Wind"</span>, <span class="at">x =</span> <span class="st">"Temp"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ST_511_Notes_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="linear-regression-equation" class="level4">
<h4 class="anchored" data-anchor-id="linear-regression-equation">Linear Regression Equation</h4>
<p>Population level: <span class="math inline">\(y=\beta_0+\beta_1*x+\epsilon\)</span></p>
<p>Sample: <span class="math inline">\(\hat{y}=\hat{\beta_0}+\hat{\beta_1}*x\)</span></p>
<ul>
<li><p><span class="math inline">\(\hat{y}\)</span> (yhat) = predicted value of y</p></li>
<li><p><span class="math inline">\(\hat{\beta_0}\)</span> (b) = estimated intercept</p></li>
<li><p><span class="math inline">\(\hat{\beta_1}\)</span> (b1) = estimated slope</p></li>
<li><p><span class="math inline">\(x\)</span> = explanatory variable</p></li>
</ul>
<p>The slope describes the estimated difference in the predicted average outcome of <span class="math inline">\(y\)</span> if the predictor variable <span class="math inline">\(x\)</span> happened to be one unit larger. The intercept describes the average outcome of <span class="math inline">\(y\)</span> if <span class="math inline">\(x\)</span> = 0 and the linear model is valid all the way to <span class="math inline">\(x\)</span> = 0 (values of <span class="math inline">\(x\)</span> = 0 are not observed or relevant in many applications)</p>
<p><img src="Images\lsq_line.png" class="img-fluid"></p>
<section id="categorical-predictors" class="level5">
<h5 class="anchored" data-anchor-id="categorical-predictors">Categorical Predictors</h5>
<p>The estimated intercept is the value of the outcome variable for the first category (i.e., the category corresponding to an indicator value of 0). The estimated slope is the average change in the outcome variable between the two categories.</p>
</section>
<section id="coefficient-of-determination" class="level5">
<h5 class="anchored" data-anchor-id="coefficient-of-determination">Coefficient of Determination</h5>
<p><span class="math inline">\(R^2\)</span> is also called the coefficient of determination, which is the proportion of variability in the outcome variable explained by the model.</p>
<p>Since <span class="math inline">\(r\)</span> is always between -1 and 1, <span class="math inline">\(R^2\)</span> will always be between 0 and 1. It measures the proportion of variation in the outcome variable, <span class="math inline">\(y\)</span>, that can be explained by the linear model with predictor <span class="math inline">\(x\)</span>.</p>
</section>
<section id="sums-of-squares" class="level5">
<h5 class="anchored" data-anchor-id="sums-of-squares">Sums of Squares</h5>
<p><img src="Images\sumofsquares.png" class="img-fluid"></p>
</section>
</section>
<section id="r-code" class="level4">
<h4 class="anchored" data-anchor-id="r-code">R-Code</h4>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching packages ────────────────────────────────────── tidymodels 1.2.0 ──</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>✔ broom        1.0.10     ✔ rsample      1.2.1 
✔ dials        1.3.0      ✔ tune         1.2.1 
✔ infer        1.0.7      ✔ workflows    1.1.4 
✔ modeldata    1.4.0      ✔ workflowsets 1.1.0 
✔ parsnip      1.2.1      ✔ yardstick    1.3.1 
✔ recipes      1.1.0      </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Conflicts ───────────────────────────────────────── tidymodels_conflicts() ──
✖ scales::discard() masks purrr::discard()
✖ dplyr::filter()   masks stats::filter()
✖ recipes::fixed()  masks stringr::fixed()
✖ dplyr::lag()      masks stats::lag()
✖ yardstick::spec() masks readr::spec()
✖ recipes::step()   masks stats::step()
• Use suppressPackageStartupMessages() to eliminate package startup messages</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term        estimate std.error statistic  p.value
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept)   23.2      2.11       11.0  4.90e-21
2 Temp          -0.170    0.0269     -6.33 2.64e- 9</code></pre>
</div>
</div>
</section>
<section id="why-mean-response" class="level4">
<h4 class="anchored" data-anchor-id="why-mean-response">Why Mean Response</h4>
<p>The phrase expected value is a synonym for mean value in the long run (meaning for meany repeats or a large sample size)</p>
<p><img src="Images\slr_image.png" class="img-fluid"></p>
</section>
<section id="null-and-alternative-hypothesis" class="level4">
<h4 class="anchored" data-anchor-id="null-and-alternative-hypothesis">Null and Alternative Hypothesis</h4>
<p><span class="math inline">\(H_o:\beta_1=0\)</span></p>
<p><span class="math inline">\(H_a:\beta_1\neq0\)</span></p>
</section>
<section id="assumptions-5" class="level4">
<h4 class="anchored" data-anchor-id="assumptions-5">Assumptions</h4>
<section id="independence" class="level5">
<h5 class="anchored" data-anchor-id="independence">Independence</h5>
<p>Most important thing is how you sample the data, with the fundamental idea being that the population you randomly sampled from had an equal chance for selection, and that the observations are independent from one another.</p>
<p>To check you will want to plot the residuals:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(airquality<span class="sc">$</span>Temp, airquality<span class="sc">$</span>res,</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Residuals"</span>,</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Temperature"</span>,</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Wind Speed Residuals"</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>     )</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">0</span>, <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ST_511_Notes_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The residuals should be randomly and symmetrically distributed around zero under all conditions, and in particular there should be no correlation between consecutive errors no matter how the rows are sorted, as long as it is on some criterion that does not involve the dependent variable. If this is not true, it could be due to a violation of the linearity assumption or due to bias that is explainable by omitted variables (say, interaction terms or dummies for identifiable conditions). <a href="https://people.duke.edu/~rnau/testing.htm">Source</a></p>
</section>
<section id="linearity" class="level5">
<h5 class="anchored" data-anchor-id="linearity">Linearity</h5>
<p>The first step is to look at a scatter plot of the data, to see if there is a clear violation of linearity. If you don’t notice a clear polynomial or logistic regression, that is a good sign of a linear relationship.</p>
<p>Non-linearity is most evident in a plot of <strong>residual vs.&nbsp;fitted (predicted) values</strong>. The points should be symmetrically distributed around a horizontal line, with a roughly constant variance. The points should appear random rather than following a specific pattern. What you are checking for is equal variance.</p>
<p><img src="Images\res_fitted.png" class="img-fluid"></p>
<p>A violation of linearity would appear to show a clear bowed pattern:</p>
<p><img src="Images\violation.png" class="img-fluid"></p>
</section>
<section id="equal-variance" class="level5">
<h5 class="anchored" data-anchor-id="equal-variance">Equal Variance</h5>
<p>Violations of homoscedasticity (which are called “heteroscedasticity”) make it difficult to gauge the true standard deviation of the forecast errors, usually resulting in confidence intervals that are too wide or too narrow, and creates inaccurate p-values. Heteroscedasticity may also have the effect of giving too much weight to a small subset of the data (namely the subset where the error variance was largest) when estimating coefficients.</p>
<p>You do not want to see the residual plot showing unequal spread of data, if there is a clear pattern as in the plot below, that is a good sign the data does not have equal variance.</p>
<p><img src="Images\homosce.png" class="img-fluid"></p>
</section>
<section id="linearity-and-equal-variance-summary" class="level5">
<h5 class="anchored" data-anchor-id="linearity-and-equal-variance-summary">Linearity and Equal Variance Summary</h5>
<p><img src="Images\resvfit.png" class="img-fluid"></p>
</section>
<section id="normality-1" class="level5">
<h5 class="anchored" data-anchor-id="normality-1">Normality</h5>
<p>We think about our sample size and also look at Normal Q-Q plots of our residuals. The residuals should roughly follow the straight line mapped by the plot, deviations would indicate the data may not meet the normality assumption. If the sample size is large the CLT would account for minor deviations, but if your sample size is small minor deviations should be carefully evaluated.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>airquality <span class="sc">|&gt;</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">sample=</span>res)) <span class="sc">+</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_qq</span>() <span class="sc">+</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_qq_line</span>(<span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Normal Q-Q Plot of Residuals"</span>,</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Model: Wind ~ Temp (Airquality Data"</span>,</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Theoretical Quantiles (Standard Normal)"</span>,</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Sample Quantiles (Residuals)"</span></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ST_511_Notes_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>A faster way to make plots for your linear regression is to just use the built in <code>plot()</code> function on your model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(air_lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ST_511_Notes_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ST_511_Notes_files/figure-html/unnamed-chunk-12-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ST_511_Notes_files/figure-html/unnamed-chunk-12-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ST_511_Notes_files/figure-html/unnamed-chunk-12-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="test-statistic-2" class="level4">
<h4 class="anchored" data-anchor-id="test-statistic-2">Test Statistic</h4>
<p><span class="math display">\[
t = \frac{\hat{\beta_1}-\beta_{null}}{SE(\hat{\beta_1})}
\]</span></p>
<section id="standard-error" class="level5">
<h5 class="anchored" data-anchor-id="standard-error">Standard Error</h5>
<p><img src="Images\se_lin.png" class="img-fluid"></p>
</section>
</section>
<section id="confidence-intervals-and-predictions" class="level4">
<h4 class="anchored" data-anchor-id="confidence-intervals-and-predictions">Confidence Intervals and Predictions</h4>
<p>How to predict true mean Wind (mph) when the Temp is 17 degrees? Note that a Temp of 17 is outside the bounds of our data, meaning we are extrapolating.</p>
<section id="response" class="level5">
<h5 class="anchored" data-anchor-id="response">Response</h5>
<p><span class="math display">\[
\hat{\mu_y} \pm t^**SE_{\hat{\mu_y}}
\]</span></p>
</section>
<section id="standard-errors" class="level5">
<h5 class="anchored" data-anchor-id="standard-errors">Standard Errors</h5>
<p><span class="math inline">\(X_{given}\)</span> = What we set X equal to</p>
<p><img src="Images\xgiven.png" class="img-fluid"></p>
<p>The term <span class="math inline">\(\frac{1}{n}\)</span> accounts for the general uncertainty in estimating the intercept.</p>
<p>The term <span class="math inline">\(\hat{\sigma}^2\)</span> in the outer square root represents the uncertainty around our prediction.</p>
<p>The uncertainty introduced by the slope (<span class="math inline">\(\hat{\beta}_1\)</span>) is accounted for by,</p>
<p><span class="math display">\[
\frac{(X_{given}-\bar{X})^2}{\sum^n_{i=1}(X_i-\bar{X})^2}
\]</span></p>
</section>
<section id="r-code-1" class="level5">
<h5 class="anchored" data-anchor-id="r-code-1">R-Code</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Wind <span class="sc">~</span> Temp, <span class="at">data =</span> airquality)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>new_temp_data <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">Temp =</span> <span class="dv">17</span>)</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  model1, </span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">newdata =</span> new_temp_data, </span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">interval =</span> <span class="st">"confidence"</span>, </span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">level =</span> <span class="fl">0.95</span></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr      upr
1 20.33579 17.05817 23.61342</code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="multiple-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="multiple-linear-regression">Multiple Linear Regression</h2>
<ul>
<li><p>Has a quantitative response (Y)</p></li>
<li><p>Has &gt; 1 explanatory variable</p></li>
<li><p>The values of the coefficients change when we add more variables into our model</p></li>
</ul>
<section id="additive-model" class="level3">
<h3 class="anchored" data-anchor-id="additive-model">Additive Model</h3>
<p>The relationship between x and y does not depend on z</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(palmerpenguins)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'palmerpenguins'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:modeldata':

    penguins</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>penguins_clean <span class="ot">&lt;-</span> penguins <span class="sc">|&gt;</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(bill_length_mm <span class="sc">!=</span> <span class="fu">is.na</span>(bill_length_mm),</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>         flipper_length_mm <span class="sc">!=</span> <span class="fu">is.na</span>(flipper_length_mm))</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating additive model</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>add_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(flipper_length_mm <span class="sc">~</span> bill_length_mm <span class="sc">+</span> species, <span class="at">data =</span> penguins_clean)</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Grabbing predictions</span></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>penguins_clean<span class="sc">$</span>pred_flipper <span class="ot">&lt;-</span> <span class="fu">predict</span>(add_model)</span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating new data to assign full x scale to</span></span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a>x_scale_df <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(</span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">bill_length_mm =</span> <span class="fu">seq</span>(</span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">from =</span> <span class="fu">min</span>(penguins_clean<span class="sc">$</span>bill_length_mm),</span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">to =</span> <span class="fu">max</span>(penguins_clean<span class="sc">$</span>bill_length_mm),</span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">by =</span> .<span class="dv">1</span>, <span class="co"># Sets the scale increments</span></span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">species =</span> <span class="fu">unique</span>(penguins_clean<span class="sc">$</span>species)</span>
<span id="cb29-19"><a href="#cb29-19" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb29-20"><a href="#cb29-20" aria-hidden="true" tabindex="-1"></a>                            </span>
<span id="cb29-21"><a href="#cb29-21" aria-hidden="true" tabindex="-1"></a>                          </span>
<span id="cb29-22"><a href="#cb29-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-23"><a href="#cb29-23" aria-hidden="true" tabindex="-1"></a><span class="co"># adding new prediction lines</span></span>
<span id="cb29-24"><a href="#cb29-24" aria-hidden="true" tabindex="-1"></a>x_scale_df<span class="sc">$</span>predline <span class="ot">&lt;-</span> <span class="fu">predict</span>(add_model, x_scale_df)</span>
<span id="cb29-25"><a href="#cb29-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-26"><a href="#cb29-26" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> penguins_clean, <span class="fu">aes</span>(<span class="at">x =</span> bill_length_mm, <span class="at">y =</span> flipper_length_mm, <span class="at">color =</span> species)) <span class="sc">+</span></span>
<span id="cb29-27"><a href="#cb29-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb29-28"><a href="#cb29-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> x_scale_df, <span class="fu">aes</span>(<span class="at">y =</span> predline), <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb29-29"><a href="#cb29-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb29-30"><a href="#cb29-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Additive Model"</span>,</span>
<span id="cb29-31"><a href="#cb29-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Model: Flipper Length ~ Bill Length + Species (Same Slope, Different Intercepts)"</span>,</span>
<span id="cb29-32"><a href="#cb29-32" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Bill Length (mm)"</span>,</span>
<span id="cb29-33"><a href="#cb29-33" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Flipper Length (mm)"</span></span>
<span id="cb29-34"><a href="#cb29-34" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb29-35"><a href="#cb29-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ST_511_Notes_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="model-output" class="level5">
<h5 class="anchored" data-anchor-id="model-output">Model Output</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(add_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 5
  term             estimate std.error statistic   p.value
  &lt;chr&gt;               &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)        148.       4.17      35.4  6.78e-116
2 bill_length_mm       1.08     0.107     10.1  3.12e- 21
3 speciesChinstrap    -5.00     1.37      -3.65 3.00e-  4
4 speciesGentoo       17.8      1.17      15.2  3.45e- 40</code></pre>
</div>
</div>
</section>
<section id="general-formula" class="level4">
<h4 class="anchored" data-anchor-id="general-formula">General Formula</h4>
<p><span class="math display">\[
\hat{Y} = \hat{\beta_0} + \hat{\beta}_1X_1 + \hat{\beta}_2X_2 + \text{...} + + \hat{\beta}_kX_k
\]</span></p>
<p>Our formula in our example would be,</p>
<p><span class="math display">\[
\hat{fl} = 147.951 + 1.083 * \text{bl} - 5.004 * \text{chin} + 17.799 * \text{gentoo}
\]</span></p>
<p><span class="math display">\[
I_{Gentoo} \{\text{1 when Gentoo, 0 for all else}
\]</span></p>
<p><span class="math display">\[
I_{Chin} \{\text{1 when Chin, 0 for all else}
\]</span></p>
<ul>
<li>147.95 represents the intercept for Adelie penguins which is our baseline reference, the formula just looking at the Adelie penguins would look like,</li>
</ul>
<p><span class="math display">\[
\hat{fl}_{Adelie} = 147.951 + 1.083 * \text{bill}
\]</span></p>
<ul>
<li>To represent just the formula for Chinstrap penguins we could use,</li>
</ul>
<p><span class="math display">\[
\hat{fl}_{Chin} = 147.951  - 5.004 + 1.083 * \text{bill}
\]</span></p>
</section>
<section id="interpretations" class="level4">
<h4 class="anchored" data-anchor-id="interpretations">Interpretations</h4>
<p>Holding species constant, for a 1mm increase in bill length, we estimate an average increase in flipper length of 1.083mm.</p>
<p>Holding bill length constant, we estimate the mean flipper length of Gentoo penguins to be 17.799mm larger than the Adelie penguins.</p>
</section>
</section>
<section id="interaction-model" class="level3">
<h3 class="anchored" data-anchor-id="interaction-model">Interaction Model</h3>
<p>The relationship between x and y depends on the value of z.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>inter_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(flipper_length_mm <span class="sc">~</span> bill_length_mm <span class="sc">*</span> species, <span class="at">data =</span> penguins_clean)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>penguins_clean <span class="sc">|&gt;</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> bill_length_mm, <span class="at">y =</span> flipper_length_mm, <span class="at">color =</span> species)</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span> </span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> F, <span class="at">formula =</span> <span class="st">"y ~ x"</span>) <span class="sc">+</span></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Interaction Model"</span>,</span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Flipper Length ~ Bill Length * Species (Non-Parallel Slopes)"</span>,</span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Bill Length (mm)"</span>,</span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Flipper Length (mm)"</span></span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ST_511_Notes_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="output" class="level4">
<h4 class="anchored" data-anchor-id="output">Output</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(inter_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  term                            estimate std.error statistic  p.value
  &lt;chr&gt;                              &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept)                      159.        6.90     23.0   4.72e-71
2 bill_length_mm                     0.800     0.178     4.50  9.17e- 6
3 speciesChinstrap                 -12.3      12.5      -0.986 3.25e- 1
4 speciesGentoo                     -7.83     10.6      -0.736 4.63e- 1
5 bill_length_mm:speciesChinstrap    0.207     0.276     0.750 4.54e- 1
6 bill_length_mm:speciesGentoo       0.591     0.246     2.40  1.67e- 2</code></pre>
</div>
</div>
<p>How would we interpret something like the 0.207 value?</p>
<p>For a 1mm increase in bill length, we estimate an average increase in flipper length of 0.207mm more for Chinstrap than Adelie penguins, holding all other variables constant.</p>
</section>
<section id="formula" class="level4">
<h4 class="anchored" data-anchor-id="formula">Formula</h4>
<p><span class="math display">\[
\hat{Y} = \hat{\beta_0} + \hat{\beta}_1X_1 + \hat{\beta}_2X_2 + \hat{\beta}_3(X_1X_2)
\]</span></p>
<p>For our example the formula would look like,</p>
<p><span class="math display">\[
\hat{fl} = 158.92  + 0.80 *bill - 12.29 * Chin - 7.83 * Gentoo + .207 * bill * Chin + .591 * bill * Gen
\]</span></p>
<p>The line for just Adelie penguins would look like,</p>
<p><span class="math display">\[
\hat{fl}_{Adelie} = 159 + .800 * bill
\]</span></p>
<p>The line for just Chinstrap penguins would look like,</p>
<p><span class="math display">\[
\hat{fl}_{Chin} = 159 - 12.29 + .800 * bill + .207 * bill
\]</span> - <span class="math inline">\(159 - 12.29\)</span> is the change to our intercept in the model while <span class="math inline">\(bill(.800 + .207)\)</span> would represent our slope</p>
</section>
<section id="assumptions-6" class="level4">
<h4 class="anchored" data-anchor-id="assumptions-6">Assumptions</h4>
<p>We use the same assumptions as the assumptions we used for singular linear regression models, but add another assumption for multicollinearity.</p>
<p>Multicollinearity happens when the predictor variables are correlated within themselves. When the predictor variables themselves are correlated, the coefficients in a multiple regression model can be difficult to interpret.</p>
<section id="multicollinearity-example" class="level5">
<h5 class="anchored" data-anchor-id="multicollinearity-example">Multicollinearity Example</h5>
<p>This is an example using fake data:</p>
<p><img src="Images\multi.png" class="img-fluid"></p>
<p><img src="Images\multi1.png" class="img-fluid"></p>
<p>The photos show how the variables react in a linear regression model on their own.</p>
<p><img src="Images\multi3.png" class="img-fluid"></p>
<p>TO check this assumption you can calculate correlation coefficients between all your predictors. You can also calculate variance inflation factors (not covered in course)</p>
</section>
</section>
</section>
<section id="hypothesis-test-for-multiple-linear-regression" class="level3">
<h3 class="anchored" data-anchor-id="hypothesis-test-for-multiple-linear-regression">Hypothesis Test for Multiple Linear Regression</h3>
<p>To illustrate this lets first look back at our examples for our simple linear regression compared to our additive multiple linear regression. Represented by the formulas,</p>
<p><span class="math display">\[
fl = \beta_0 + \beta_1 * bill + \epsilon
\]</span></p>
<p><span class="math display">\[
fl = \beta_0 + \beta_1 * bill + \beta_2 * Chin + \beta_3  * Gentoo + \epsilon
\]</span></p>
<p>The question is to try and determine if the multiple linear regression model is worth it. One thing to remember is that you are never going to get worse at predicting your response variable by adding extra terms, you are merely checking if adding those extra terms are worth it.</p>
<section id="notation-5" class="level4">
<h4 class="anchored" data-anchor-id="notation-5">Notation</h4>
<p><span class="math inline">\(H_0: \beta_2 = \beta_3 = 0\)</span></p>
<p><span class="math inline">\(H_a: \text{At least one of the betas differ from zero}\)</span></p>
<p>The idea is to see if the reduction in unexplained variance (the reduction in Residual Sum of Squares, RSS) when moving from <span class="math inline">\(Model_{reduced}\)</span> to <span class="math inline">\(Model_{full}\)</span> is statistically significant. In other words, is species a good predictor to include in our analysis.</p>
</section>
<section id="test-statistic-3" class="level4">
<h4 class="anchored" data-anchor-id="test-statistic-3">Test Statistic</h4>
<p><span class="math display">\[
F = \frac{(RSS_R-RSS_f)/(df_R-df_F)}{MSE_F}
\]</span></p>
<p><span class="math inline">\(df_F = n - k_F -1\)</span>: n is our sample size, while k is the number of predictors</p>
<p><span class="math inline">\(df_R = n - k_R -1\)</span>: n is our sample size, while k is the number of predictors</p>
<ul>
<li>F represents our full model, while R represents our reduced model.</li>
</ul>
<section id="visualization" class="level5">
<h5 class="anchored" data-anchor-id="visualization">Visualization</h5>
<p>We are comparing the Residual Sum of Squares between the two models</p>
<p>Reduced Model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fitting a linear model</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>peng_slm <span class="ot">&lt;-</span> <span class="fu">lm</span>(flipper_length_mm <span class="sc">~</span> bill_length_mm, <span class="at">data =</span> penguins_clean) </span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating clone df</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>peng_clone <span class="ot">&lt;-</span> penguins_clean</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Adding fitted and residuals </span></span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>peng_clone<span class="sc">$</span>fit  <span class="ot">&lt;-</span> <span class="fu">fitted</span>(peng_slm)</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>peng_clone<span class="sc">$</span>res  <span class="ot">&lt;-</span> <span class="fu">resid</span>(peng_slm)</span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating residual overlay plot</span></span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(peng_clone, <span class="fu">aes</span>(<span class="at">x =</span> bill_length_mm, <span class="at">y =</span> flipper_length_mm)) <span class="sc">+</span></span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>(</span>
<span id="cb36-14"><a href="#cb36-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">xend =</span> bill_length_mm, <span class="at">yend =</span> fit), </span>
<span id="cb36-15"><a href="#cb36-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">'black'</span>,</span>
<span id="cb36-16"><a href="#cb36-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">linetype =</span> <span class="st">'dotted'</span>,</span>
<span id="cb36-17"><a href="#cb36-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fl">0.5</span></span>
<span id="cb36-18"><a href="#cb36-18" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span> </span>
<span id="cb36-19"><a href="#cb36-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> F, <span class="at">formula =</span> y <span class="sc">~</span> x, <span class="at">color =</span> <span class="st">"purple"</span>) <span class="sc">+</span></span>
<span id="cb36-20"><a href="#cb36-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">'darkorange'</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb36-21"><a href="#cb36-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb36-22"><a href="#cb36-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Residual Distances for the Reduced Model"</span>, </span>
<span id="cb36-23"><a href="#cb36-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Model: Flipper Length ~ Bill Length. Vertical lines show model error (residuals)"</span>,</span>
<span id="cb36-24"><a href="#cb36-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Bill Length (mm)"</span>, </span>
<span id="cb36-25"><a href="#cb36-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Flipper Length (mm)"</span></span>
<span id="cb36-26"><a href="#cb36-26" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb36-27"><a href="#cb36-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ST_511_Notes_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Full Model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fitting a linear model</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>peng_flm <span class="ot">&lt;-</span> <span class="fu">lm</span>(flipper_length_mm <span class="sc">~</span> bill_length_mm <span class="sc">+</span> species, <span class="at">data =</span> penguins_clean) </span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating clone df</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>peng_clone1 <span class="ot">&lt;-</span> penguins_clean</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Adding fitted observations to df</span></span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>peng_clone1<span class="sc">$</span>fit  <span class="ot">&lt;-</span> <span class="fu">fitted</span>(peng_flm)</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating residual overlay plot</span></span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(peng_clone1, <span class="fu">aes</span>(<span class="at">x =</span> bill_length_mm, <span class="at">y =</span> flipper_length_mm, <span class="at">color =</span> species)) <span class="sc">+</span></span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>( </span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">xend =</span> bill_length_mm, <span class="at">yend =</span> fit), <span class="co"># draws a line from observed points to fitted value</span></span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"black"</span>,</span>
<span id="cb37-15"><a href="#cb37-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">linetype =</span> <span class="st">'dotted'</span>,</span>
<span id="cb37-16"><a href="#cb37-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fl">0.5</span></span>
<span id="cb37-17"><a href="#cb37-17" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb37-18"><a href="#cb37-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb37-19"><a href="#cb37-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> fit), <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span> <span class="co"># y = fit is the values created from the linear model</span></span>
<span id="cb37-20"><a href="#cb37-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb37-21"><a href="#cb37-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Residual Distances for the Full Additive Model (Forced Parallel Lines)"</span>, </span>
<span id="cb37-22"><a href="#cb37-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Model: Flipper Length ~ Bill Length + Species"</span>,</span>
<span id="cb37-23"><a href="#cb37-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Bill Length (mm)"</span>, </span>
<span id="cb37-24"><a href="#cb37-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Flipper Length (mm)"</span></span>
<span id="cb37-25"><a href="#cb37-25" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb37-26"><a href="#cb37-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ST_511_Notes_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>You can compare the length of the distance between residuals and how that compares between a singular line versus multiple lines.</p>
</section>
</section>
<section id="assumptions-7" class="level4">
<h4 class="anchored" data-anchor-id="assumptions-7">Assumptions</h4>
<p>You need to check for both models:</p>
<ul>
<li><p>Independence</p>
<ul>
<li>Same as with simple linear regression you just want to make sure it is reasonable your data is independent. You will want a simple random sample</li>
</ul></li>
<li><p>Linearity</p></li>
<li><p>Normality of Residuals</p></li>
<li><p>Equal Variance</p></li>
<li><p>Nested models</p></li>
</ul>
<section id="linearity-and-equal-variance" class="level5">
<h5 class="anchored" data-anchor-id="linearity-and-equal-variance">Linearity and Equal Variance</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Adding residuals to df</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>peng_clone1<span class="sc">$</span>res <span class="ot">&lt;-</span> <span class="fu">resid</span>(peng_flm) </span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="co"># residual plot vs fitted</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> peng_clone1, <span class="fu">aes</span>(<span class="at">x =</span> fit, <span class="at">y =</span> res)) <span class="sc">+</span></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">yintercept =</span> <span class="dv">0</span>,</span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">'red'</span>,</span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">linetype =</span> <span class="st">'dashed'</span>,</span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> <span class="dv">1</span></span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(</span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">method =</span> <span class="st">'loess'</span>,</span>
<span id="cb38-15"><a href="#cb38-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">se =</span> F,</span>
<span id="cb38-16"><a href="#cb38-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">'blue'</span>,</span>
<span id="cb38-17"><a href="#cb38-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> <span class="dv">1</span></span>
<span id="cb38-18"><a href="#cb38-18" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb38-19"><a href="#cb38-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb38-20"><a href="#cb38-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Residuals vs Fitted Plot"</span>,</span>
<span id="cb38-21"><a href="#cb38-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Model: Flipper Length ~ Species + Bill Length"</span>,</span>
<span id="cb38-22"><a href="#cb38-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Fitted Values (Predicted Flipper Length)"</span>,</span>
<span id="cb38-23"><a href="#cb38-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Residuals (Error)"</span></span>
<span id="cb38-24"><a href="#cb38-24" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb38-25"><a href="#cb38-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ST_511_Notes_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Based on this plot we can see that the residuals are fairly randomly distributed around zero indicating the data meets the linearity assumption. For equal variance we want to see the data is spread across the plot without creating an imbalance between any specific part along the x-axis. Since the residuals are not fanning out or funneling into to any specific point, we can state the model meets the assumption of equal variance.</p>
</section>
<section id="normality-2" class="level5">
<h5 class="anchored" data-anchor-id="normality-2">Normality</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>peng_clone1 <span class="sc">|&gt;</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">sample =</span> res)) <span class="sc">+</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_qq</span>(<span class="at">color =</span> <span class="st">'darkgreen'</span>) <span class="sc">+</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_qq_line</span>(<span class="at">color =</span> <span class="st">'black'</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Normal Q-Q Plot of Residuals for Flipper Length Model"</span>,</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Model: Flipper Length ~ Species + Bill Length"</span>,</span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Theoretical Quantiles (Normal Distribution)"</span>,</span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Sample Quantiles (Model Residuals)"</span></span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ST_511_Notes_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Since we have a large sample size we are more robust to deviations of normality, so we can be robust to the outlier seen on the left tail of our plot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(peng_flm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ST_511_Notes_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ST_511_Notes_files/figure-html/unnamed-chunk-22-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ST_511_Notes_files/figure-html/unnamed-chunk-22-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ST_511_Notes_files/figure-html/unnamed-chunk-22-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="nested-models" class="level5">
<h5 class="anchored" data-anchor-id="nested-models">Nested Models</h5>
<p>Your reduced model has to be inside your full model, otherwise it will create negative values that will impact the ability to calculate your test statistic.</p>
</section>
</section>
<section id="r-code-for-anova-for-comparisons" class="level4">
<h4 class="anchored" data-anchor-id="r-code-for-anova-for-comparisons">R-Code for Anova for Comparisons</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>model_reduced <span class="ot">&lt;-</span> <span class="fu">lm</span>(flipper_length_mm <span class="sc">~</span> bill_length_mm, <span class="at">data =</span> penguins)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>model_full <span class="ot">&lt;-</span> <span class="fu">lm</span>(flipper_length_mm <span class="sc">~</span> bill_length_mm <span class="sc">+</span> species, <span class="at">data =</span> penguins)</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(model_reduced, model_full)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: flipper_length_mm ~ bill_length_mm
Model 2: flipper_length_mm ~ bill_length_mm + species
  Res.Df   RSS Df Sum of Sq      F    Pr(&gt;F)    
1    340 38394                                  
2    338 11471  2     26923 396.64 &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The DF column difference in residual degrees of freedom between the two adjacent models being compared. This is the numerator degrees of freedom for the F-test. The denominator degrees of freedom is the Residual degrees of freedom from the full model (338).</p>
<p>The 26923 is the reduction in the Residual Sum of Squares (RSS) from the reduced to full model.</p>
<p>Our p-value comes from a F-distribution with 2 and 338 degrees of freedom.</p>
<section id="interpretation" class="level5">
<h5 class="anchored" data-anchor-id="interpretation">Interpretation</h5>
<p>Since our p-value is really small we can reject the null hypothesis, and state that the amount of variation in flipper length explained by the addition of species is statistically significant.</p>
</section>
</section>
<section id="additive-vs-interaction-model" class="level4">
<h4 class="anchored" data-anchor-id="additive-vs-interaction-model">Additive vs Interaction Model</h4>
<p>Additive:</p>
<p><span class="math display">\[
fl = \beta_0 + \beta_1 * bill + \beta_2 * Chin + \beta_3  * Gentoo + \epsilon
\]</span></p>
<p>Interaction:</p>
<p><span class="math display">\[
fl = \beta_0 + \beta_1 * bill + \beta_2 * Chin + \beta_3  * Gentoo + \beta_4*bill*Chin + \beta_5 * bill * Gentoo + \epsilon
\]</span></p>
<p>Since we previously plotted our residuals for our additive model lets see what it would look like on our interaction model</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fitting a linear model</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>peng_flm <span class="ot">&lt;-</span> <span class="fu">lm</span>(flipper_length_mm <span class="sc">~</span> bill_length_mm <span class="sc">*</span> species, <span class="at">data =</span> penguins_clean) </span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating clone df</span></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>peng_clone1 <span class="ot">&lt;-</span> penguins_clean</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Adding fitted observations to df</span></span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>peng_clone1<span class="sc">$</span>fit  <span class="ot">&lt;-</span> <span class="fu">fitted</span>(peng_flm)</span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating residual overlay plot</span></span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(peng_clone1, <span class="fu">aes</span>(<span class="at">x =</span> bill_length_mm, <span class="at">y =</span> flipper_length_mm, <span class="at">color =</span> species)) <span class="sc">+</span></span>
<span id="cb44-12"><a href="#cb44-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>( </span>
<span id="cb44-13"><a href="#cb44-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">xend =</span> bill_length_mm, <span class="at">yend =</span> fit), <span class="co"># draws a line from observed points to fitted value</span></span>
<span id="cb44-14"><a href="#cb44-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"black"</span>,</span>
<span id="cb44-15"><a href="#cb44-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">linetype =</span> <span class="st">'dotted'</span>,</span>
<span id="cb44-16"><a href="#cb44-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fl">0.5</span></span>
<span id="cb44-17"><a href="#cb44-17" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb44-18"><a href="#cb44-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb44-19"><a href="#cb44-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> fit), <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span> <span class="co"># y = fit is the values created from the linear model</span></span>
<span id="cb44-20"><a href="#cb44-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb44-21"><a href="#cb44-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Residuals for the Full Interaction Model"</span>, </span>
<span id="cb44-22"><a href="#cb44-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Fitted Lines: Flipper Length ~ Bill Length * Species (Different Slopes and Intercepts"</span>,</span>
<span id="cb44-23"><a href="#cb44-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Bill Length (mm)"</span>, </span>
<span id="cb44-24"><a href="#cb44-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Flipper Length (mm)"</span></span>
<span id="cb44-25"><a href="#cb44-25" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb44-26"><a href="#cb44-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ST_511_Notes_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="anova-comparison" class="level5">
<h5 class="anchored" data-anchor-id="anova-comparison">Anova Comparison</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>model_additive <span class="ot">&lt;-</span> <span class="fu">lm</span>(flipper_length_mm <span class="sc">~</span> bill_length_mm <span class="sc">+</span> species, <span class="at">data =</span> penguins_clean)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>model_interaction <span class="ot">&lt;-</span> <span class="fu">lm</span>(flipper_length_mm <span class="sc">~</span> bill_length_mm <span class="sc">*</span> species, <span class="at">data =</span> penguins_clean)</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(model_additive, model_interaction)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: flipper_length_mm ~ bill_length_mm + species
Model 2: flipper_length_mm ~ bill_length_mm * species
  Res.Df   RSS Df Sum of Sq      F  Pr(&gt;F)  
1    338 11471                              
2    336 11272  2    199.66 2.9759 0.05235 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="hypothesis-notation-2" class="level5">
<h5 class="anchored" data-anchor-id="hypothesis-notation-2">Hypothesis Notation</h5>
<p><span class="math inline">\(H_0: \beta_4 = \beta_5 = 0\)</span></p>
<p><span class="math inline">\(H_A:\)</span> At least one of <span class="math inline">\(\beta_4 \ \text{or} \ \beta_5 \ne 0\)</span></p>
<p>At a significance level of <span class="math inline">\(\alpha = 0.05\)</span> and a p-value of 0.0523 we fail to reject the null hypothesis. Due to the closeness to the <span class="math inline">\(\alpha\)</span> level we can state there is weak evidence that the addition of interaction effect between bill length and species better explains the variation in flipper length over our Additive model.</p>
</section>
</section>
</section>
</section>
</section>
<section id="week-14-15" class="level1">
<h1>Week 14-15</h1>
<section id="statistical-inference-vs-sampling-variability" class="level2">
<h2 class="anchored" data-anchor-id="statistical-inference-vs-sampling-variability">Statistical Inference vs Sampling Variability</h2>
<p>Statistical Inference - taking a sample, and making claims about a larger population.</p>
<p>Sampling Variability - the natural variability (error) we expect/see from sample to sample.</p>
<ul>
<li><p>Ex: Let’s assume that Gen-Z has a mean credit score of 680 (μ=680). If you take a random sample of 100 Gen-Z individuals, would we expect the mean credit score of those 100 to be exactly 680?</p>
<ul>
<li>No, we would not assume it be the exact same mean. Because we know this, we account for sampling variability by using distributions (instead of just point estimates) when trying to make claims about an entire population (Stastical Inference)!</li>
</ul></li>
</ul>
<section id="scenarios" class="level3">
<h3 class="anchored" data-anchor-id="scenarios">Scenarios</h3>
<p>It’s important for us to know when methods are vs are not appropriate, based on variable type. We are going to go through three examples and identify each scenario on which methods would be most appropriate to answer the research question.</p>
<section id="example-1-1" class="level4">
<h4 class="anchored" data-anchor-id="example-1-1">Example 1</h4>
<p>An ecologist is studying a population of small mammals (e.g., field mice) to see if their primary habitat is associated with their dominant predator avoidance tactic. The study aims to determine if animals that live in dense forest prefer to hide, while those in open fields prefer to flee.</p>
<p><img src="Images\ex1.png" class="img-fluid"></p>
<ul>
<li>This would use a Chi-Square Distribution, thus statistical inference is used.</li>
</ul>
</section>
<section id="example-2" class="level4">
<h4 class="anchored" data-anchor-id="example-2">Example 2</h4>
<p>What was the median student loan debt for all 350 students who graduated from the Engineering School in May 2025?</p>
<ul>
<li>This would not need any form of statistical inference as your population of interest would be all 350 students, thus sampling variability does not need to be accounted for.</li>
</ul>
</section>
<section id="example-3" class="level4">
<h4 class="anchored" data-anchor-id="example-3">Example 3</h4>
<p>A pharmacologist is studying the factors that influence patient Recovery Time (in days) following a specific surgical procedure. They are analyzing the effects of a new post-operative drug and the patient’s age.</p>
<p>The researcher hypothesizes a significant interaction between the two factors: the new drug may be highly effective (significantly reducing recovery time) for younger patients, but its efficacy might be greatly reduced or even disappear for older patients due to metabolic changes.</p>
<ul>
<li>Since this would be looking at a categorical explanatory variable (new drug or no new drug) with an interaction effect using a quantitative explanatory variable (age of patient) analyze a quantitative response variable (recovery time) the best option would be to conduct statistical inference using regression.</li>
</ul>
</section>
</section>
</section>
<section id="logistic-regression" class="level2">
<h2 class="anchored" data-anchor-id="logistic-regression">Logistic Regression</h2>
<p>Logistic regression is a modeling tool used for a categorical response variable. Is very similar to linear regression, but obviously the response variable is different.</p>
<section id="the-problem" class="level3">
<h3 class="anchored" data-anchor-id="the-problem">The Problem</h3>
<p><span class="math inline">\((\mu_y) = (\beta_0 + \beta_1X_1 + ...)\)</span></p>
<ul>
<li>The right side of a regression equation, which cant take any value from <span class="math inline">\(-\infty\)</span> to <span class="math inline">\(\infty\)</span>.</li>
</ul>
<p><span class="math inline">\((\mu)\)</span>: The expected value of the response variable, which is restricted to a certain range (e.g.&nbsp;a probability must be between 0 and 1).</p>
<p>Applying a specific mathematical transformation to the expected outcome (or mean) of your model in order to linearly relate it to your predictor variables, while restricting the values of your response variable accordingly.</p>
<p>For logistic regression, this is the logit-link function:</p>
<p><span class="math inline">\((\mu_y \ or \ p)\)</span></p>
<p><span class="math inline">\(ln(\frac{p}{1-p})\)</span> = log - odds</p>
<ul>
<li><p><span class="math inline">\(p\)</span> = probability of success</p></li>
<li><p><span class="math inline">\(1-p\)</span> = probability of failure</p></li>
<li><p>odds = <span class="math inline">\(\frac{p}{1-p}\)</span></p></li>
</ul>
<p><span class="math inline">\(\widehat{ln(\frac{p}{1-p})} = \hat{\beta}_0 +\hat{\beta}_1X_1+...\)</span></p>
</section>
<section id="generalized-linear-model-glm" class="level3">
<h3 class="anchored" data-anchor-id="generalized-linear-model-glm">Generalized Linear Model (GLM)</h3>
<p>GLM is another term for a type of logistic regression model. Where we want to fit an S curve and model the probablity of success as a function of explanatory variable(s).</p>
<p><img src="Images/log_curve.png" class="img-fluid"></p>
<section id="terms" class="level4">
<h4 class="anchored" data-anchor-id="terms">Terms</h4>
<p>Bernoulli Distribution:</p>
<ul>
<li><p>2 outcomes: Success (p) or Failure (1-p)</p></li>
<li><p><span class="math inline">\(y_i\)</span> ~ Bern(p)</p></li>
<li><p>We use <span class="math inline">\(p_i\)</span> for estimated probabilities</p></li>
</ul>
</section>
<section id="the-model" class="level4">
<h4 class="anchored" data-anchor-id="the-model">The model</h4>
<p><span class="math display">\[
\widehat{ln(\frac{p}{1-p})} = \hat{\beta_o} + \hat{\beta_1}X_1 + ...
\]</span></p>
<ul>
<li><p><span class="math inline">\(ln(\frac{p}{1-p})\)</span> is called the logit link function, and can take on values from <span class="math inline">\(-\infty\)</span> to <span class="math inline">\(\infty\)</span></p></li>
<li><p><span class="math inline">\(ln(\frac{p}{1-p})\)</span> represents the log odds of a success</p></li>
</ul>
<section id="log-odds" class="level5">
<h5 class="anchored" data-anchor-id="log-odds">Log Odds</h5>
<p><span class="math inline">\(ln(\frac{p}{1-p})\)</span> = natural logarithm of the odds, where the odds are the ratio of the probability of an event happening to the probability of it not happening.</p>
<p><span class="math inline">\(ln(\frac{p}{1-p})\)</span> has good modeling properties (ex. unbounded; handles extreme values of p well for linearity; restricts p to be between 0 and 1), but it is hard to interpret. Think of this as our initial model, that we will work with to model probabilities (can also model odds).</p>
<ul>
<li><p><span class="math inline">\(p\)</span> stands for probability</p></li>
<li><p>The logit link function restricts p to be between the values [0, 1]</p></li>
</ul>
</section>
</section>
<section id="math" class="level4">
<h4 class="anchored" data-anchor-id="math">Math</h4>
<p>We want to model probabilities. We want to isolate <span class="math inline">\(p\)</span> on the left side of the equation,</p>
<p><span class="math display">\[
\widehat{ln(\frac{p}{1-p})} = \hat{\beta_o} + \hat{\beta_1}X_1 + ...
\]</span></p>
<p>To isolate the <span class="math inline">\(p\)</span> we get rid of the <span class="math inline">\(ln\)</span> by,</p>
<p><span class="math display">\[
e^{ln(\frac{p}{1-p})} = e^{\beta_0+\beta_1X1}
\]</span></p>
<p><span class="math display">\[
\frac{p}{1-p} = e^{\beta_0+\beta_1X1}
\]</span></p>
<p>Times each side by <span class="math inline">\((1-p)\)</span>,</p>
<p><span class="math display">\[
p = e^{\beta_0+\beta_1X1} * (1-p)
\]</span></p>
<p><span class="math display">\[
p = e^{\beta_0+\beta_1X1} - pe^{\beta_0+\beta_1X1}
\]</span></p>
<p>Add the new <span class="math inline">\(p*e\)</span> term to the other side,</p>
<p><span class="math display">\[
p +pe^{\beta_0+\beta_1X1} = e^{\beta_0+\beta_1X1}
\]</span></p>
<p>Simplify the equation to just one p,</p>
<p><span class="math display">\[
p(1+e^{\beta_0+\beta_1X1}) = e^{\beta_0+\beta_1X1}
\]</span></p>
<p>Divide both side by the <span class="math inline">\((1+e)\)</span> term,</p>
<p><span class="math display">\[
p = \frac{e^{\beta_0+\beta_1X1}}{1+e^{\beta_0+\beta_1X1}} \ \text{where} \ p = [0,1]
\]</span></p>
<section id="final-model" class="level5">
<h5 class="anchored" data-anchor-id="final-model">Final Model</h5>
<p><span class="math display">\[
\hat{p} = \frac{e^{\hat{\beta_0}+\hat{\beta_1}X1}}{1+e^{\hat{\beta_0}+\hat{\beta_1}X1}} \ \text{where} \ p = [0,1]
\]</span></p>
</section>
</section>
<section id="recap" class="level4">
<h4 class="anchored" data-anchor-id="recap">Recap</h4>
<p>With a categorical response variable, we use the logit link (logistic function) to calculate the log odds of a success,</p>
<p><span class="math display">\[
\widehat{ln(\frac{p}{1-p})} = \hat{\beta_o} + \hat{\beta_1}X_1 + ...
\]</span></p>
<p>We can use the same model to estimate the probability of a success,</p>
<p><span class="math display">\[
\hat{p} = \frac{e^{\hat{\beta_0}+\hat{\beta_1}X1}}{1+e^{\hat{\beta_0}+\hat{\beta_1}X1}} \ \text{where} \ p = [0,1]
\]</span></p>
<p><img src="Images/pred_probs.png" class="img-fluid"></p>
</section>
<section id="prediction-interval" class="level4">
<h4 class="anchored" data-anchor-id="prediction-interval">Prediction Interval</h4>
<p><span class="math display">\[
\hat{p} \pm ME
\]</span></p>
<p><span class="math inline">\(ME = t^* * SE(\hat{p})\)</span></p>


</section>
</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>